import streamlit as st

st.title("NPSpecDB")
st.markdown('### Database of predicted spectral properties of metabolites')

st.image('data/intro_img.jpg')

st.markdown('Art Generated by Microsft COPILOT, Powered by DALL·E 3')
